module.exports = {
    dingtalkGetAccessToken: require('./dingtalkGetAccessToken'),
    dingtalkGetUserId: require('./dingtalkGetUserId'),
    dingtalkGetAuthCode: require('./dingtalkGetAuthCode'),
    dingtalkGetSsoUserInfo: require('./dingtalkGetSsoUserInfo'),
    dingtalkGetUserAccessToken: require('./dingtalkGetUserAccessToken'),
    dingtalkGetContactUser: require('./dingtalkGetContactUser'),
    dingtalkGetUserIdByUnionid: require('./dingtalkGetUserIdByUnionid'),
    dingtalkGetUserInfo: require('./dingtalkGetUserInfo'),
    dingtalkGetAuthinfo: require('./dingtalkGetAuthinfo'),
    dingtalkInitializeSpace: require('./dingtalkInitializeSpace'),
    createSpacesUsers: require('./createSpacesUsers'),
    dingtalkStoreSuiteTicket: require('./dingtalkStoreSuiteTicket'),
    dingtalkgetConfigurations: require('./dingtalkgetConfigurations'),
}